- name: DTV02-4TS_ST1
  types:
    - GR
    - BS
    - CS
  command: recpt1 --b25 --device /dev/isdb6014video0 <channel> - -
  isDisabled: false

- name: DTV02-4TS_ST2
  types:
    - GR
    - BS
    - CS
  command: recpt1 --b25 --device /dev/isdb6014video1 <channel> - -
  isDisabled: false

- name: DTV02-4TS_ST3
  types:
    - GR
    - BS
    - CS
  command: recpt1 --b25 --device /dev/isdb6014video2 <channel> - -
  isDisabled: false

- name: DTV02-4TS_ST4
  types:
    - GR
    - BS
    - CS
  command: recpt1 --b25 --device /dev/isdb6014video3 <channel> - -
  isDisabled: false
